services:
  - type: web
    name: heart-disease-prediction
    env: python
    build:
      os: ubuntu22.04
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:app